// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import React from 'react';

import { IconName } from '../Icon';

import { TextButton } from './TextButton';

import { TextButtonSize } from '.';

/**
 * -- This file was auto-generated by Code Connect --
 * React web implementation of TextButton component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TextButton,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=1%3A398',
  {
    props: {
      size: figma.enum('size', {
        BodyMd: TextButtonSize.BodyMd,
        BodySm: TextButtonSize.BodySm,
      }),
      isDisabled: figma.boolean('isDisabled'),
      isInverse: figma.boolean('isInverse'),
      startIconName: figma.boolean('startIcon (Figma Only)', {
        true: IconName.Add,
        false: undefined,
      }),
      endIconName: figma.boolean('endIcon (Figma Only)', {
        true: IconName.Add,
        false: undefined,
      }),
    },
    example: ({
      size,
      isDisabled,
      isInverse,
      startIconName,
      endIconName,
      ...props
    }) => (
      <TextButton
        size={size}
        isDisabled={isDisabled}
        isInverse={isInverse}
        startIconName={startIconName}
        endIconName={endIconName}
        {...props}
      >
        Text button
      </TextButton>
    ),
  },
);
