// import figma needs to remain as figma otherwise it breaks code connect
// eslint-disable-next-line import-x/no-named-as-default
import figma from '@figma/code-connect';
import { TextVariant } from '@metamask/design-system-shared';
import React from 'react';

import { TextButton } from './TextButton';

/**
 * -- This file was auto-generated by Code Connect --
 * React Native implementation of TextButton component
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TextButton,
  'https://www.figma.com/design/1D6tnzXqWgnUC3spaAOELN/%F0%9F%A6%8A-MMDS-Components?node-id=1%3A398',
  {
    props: {
      size: figma.enum('size', {
        BodyMd: TextVariant.BodyMd,
        BodySm: TextVariant.BodySm,
      }),
    },
    example: ({ size, ...props }) => (
      <TextButton {...props} variant={size} onPress={() => undefined}>
        Text button
      </TextButton>
    ),
  },
);
